import { DataTypes, QueryInterface } from 'sequelize';

module.exports = {
  async up(queryInterface: QueryInterface): Promise<void> {
    await queryInterface.createTable('document_types', {
      id: {
        type: DataTypes.INTEGER.UNSIGNED,
        autoIncrement: true,
        primaryKey: true,
      },
      code: {
        type: DataTypes.STRING(50),
        allowNull: false,
        unique: true,
      },
      label_fr: {
        type: DataTypes.STRING(255),
        allowNull: false,
      },
      label_en: {
        type: DataTypes.STRING(255),
        allowNull: false,
      },
      validity_months: {
        type: DataTypes.INTEGER.UNSIGNED,
        allowNull: true,
      },
      is_required: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false,
      },
      required_for_profiles: {
        type: DataTypes.JSON,
        allowNull: false,
      },
      sort_order: {
        type: DataTypes.INTEGER.UNSIGNED,
        allowNull: false,
        defaultValue: 0,
      },
      created_at: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: DataTypes.NOW,
      },
      updated_at: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: DataTypes.NOW,
      },
    });

    await queryInterface.addIndex('document_types', ['code'], { unique: true });

    await queryInterface.bulkInsert('document_types', [
      {
        code: 'identity_card',
        label_fr: "Carte Nationale d'Identite",
        label_en: 'National ID Card',
        validity_months: null,
        is_required: true,
        required_for_profiles: JSON.stringify(['all']),
        sort_order: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        code: 'passport',
        label_fr: 'Passeport',
        label_en: 'Passport',
        validity_months: null,
        is_required: false,
        required_for_profiles: JSON.stringify(['all']),
        sort_order: 2,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        code: 'residence_permit',
        label_fr: 'Titre de sejour',
        label_en: 'Residence Permit',
        validity_months: null,
        is_required: false,
        required_for_profiles: JSON.stringify(['all']),
        sort_order: 3,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        code: 'proof_of_residence',
        label_fr: 'Justificatif de domicile',
        label_en: 'Proof of Residence',
        validity_months: 3,
        is_required: true,
        required_for_profiles: JSON.stringify(['all']),
        sort_order: 4,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        code: 'payslip',
        label_fr: 'Bulletin de salaire',
        label_en: 'Payslip',
        validity_months: 3,
        is_required: true,
        required_for_profiles: JSON.stringify(['employee_cdi', 'employee_cdd']),
        sort_order: 5,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        code: 'employment_contract',
        label_fr: 'Contrat de travail',
        label_en: 'Employment Contract',
        validity_months: null,
        is_required: true,
        required_for_profiles: JSON.stringify(['employee_cdi', 'employee_cdd']),
        sort_order: 6,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        code: 'tax_notice',
        label_fr: "Avis d'imposition",
        label_en: 'Tax Notice',
        validity_months: 12,
        is_required: true,
        required_for_profiles: JSON.stringify(['all']),
        sort_order: 7,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        code: 'student_card',
        label_fr: 'Carte etudiante',
        label_en: 'Student Card',
        validity_months: 12,
        is_required: true,
        required_for_profiles: JSON.stringify(['student']),
        sort_order: 8,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        code: 'scholarship_proof',
        label_fr: 'Justificatif de bourse',
        label_en: 'Scholarship Proof',
        validity_months: 12,
        is_required: false,
        required_for_profiles: JSON.stringify(['student']),
        sort_order: 9,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        code: 'kbis',
        label_fr: 'Extrait KBIS',
        label_en: 'KBIS Extract',
        validity_months: 3,
        is_required: true,
        required_for_profiles: JSON.stringify(['freelance']),
        sort_order: 10,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        code: 'balance_sheet',
        label_fr: 'Bilan comptable',
        label_en: 'Balance Sheet',
        validity_months: 12,
        is_required: true,
        required_for_profiles: JSON.stringify(['freelance']),
        sort_order: 11,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        code: 'pension_statement',
        label_fr: 'Attestation de retraite',
        label_en: 'Pension Statement',
        validity_months: 12,
        is_required: true,
        required_for_profiles: JSON.stringify(['retired']),
        sort_order: 12,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        code: 'bank_details',
        label_fr: 'RIB',
        label_en: 'Bank Details (RIB)',
        validity_months: null,
        is_required: false,
        required_for_profiles: JSON.stringify(['all']),
        sort_order: 13,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  async down(queryInterface: QueryInterface): Promise<void> {
    await queryInterface.dropTable('document_types');
  },
};
